export const options = [
  "여드름",
  "아토피",
  "민감성",
  "저항성",
  "10대",
  "20대",
  "30대",
  "40대+",
  "모닝",
  "나이트",
  "남성",
  "여성",
];

export const items = [
  {
    title: "사막피부를 촉촉하게",
    routine: "사하라사막님의 루틴",
    skinType: "건성",
    gender: "여성",
    tags: ["태그1", "태그2", "태그3"],
    price: 999999,
    rating: 4.9,
    reviews: 1192,
  },
  {
    title: "피부 탄력을 증가시키는 제품",
    routine: "탄력피부님의 루틴",
    skinType: "지성",
    gender: "남성",
    tags: ["태그A", "태그B", "태그C"],
    price: 750000,
    rating: 4.7,
    reviews: 980,
  },
  {
    title: "모공을 관리하는 루틴",
    routine: "모공청소부님의 루틴",
    skinType: "복합성",
    gender: "여성",
    tags: ["태그X", "태그Y", "태그Z"],
    price: 850000,
    rating: 4.8,
    reviews: 1030,
  },
];
