export const REPOSITORY_TOKENS = {
    UserRepository: Symbol('UserRepository'),
    AddressRepository: Symbol('AddressRepository'),
    RoutineRepository: Symbol('RoutineRepository'),
    CartRepository: Symbol('CartRepository'),
    ItemRepository: Symbol('ItemRepository'),
    SkinAttributeRepository: Symbol('SkinAttributeRepository'),
    UserSkinRelationRepository: Symbol('UserSkinRelationRepository'),
    RoutineSkinRelationRepository: Symbol('RoutineSkinRelationRepository'),
    RoutineTagRelationRepository: Symbol('RoutineTagRelationRepository'),
    TagRepository: Symbol('TagRepository'),
    ItemOrderRepository: Symbol('ItemOrderRepository'),
    OrderDetailRepository: Symbol('OrderDetailRepository'),
    ReviewRepository: Symbol('ReviewRepository'),
    RoutineDetailRepository: Symbol('RoutineDetailRepository'),
} as const;